chore: Fix macOS build of stressgres (#5711)
## What

Conditionally enable `dst` for `stressgres`.

## Why

`antithesis-instrumentation` does not build on macOS, but isn't intended
to. Attempting to build it can cause `cargo check`/`cargo clippy` to
fail with:
```console
  error: invalid Mach-O section specifier
    --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/antithesis-instrumentation-0.1.0/src/lib.rs:10:25
     |
  10 | #[unsafe(link_section = ".init_array")]
     |                         ^^^^^^^^^^^^^ not a valid Mach-O section specifier
     |
     = note: a Mach-O section specifier requires a segment and a section, separated by a comma
     = help: an example of a valid Mach-O section specifier is `__TEXT,__cstring`

  error: could not compile `antithesis-instrumentation` (lib) due to 1 previous error
```