fix: Fix error for invalid col in FF JSON (#3218)
The error used to say the column didn't exist in the table, but what
it's actually trying to say is that the column isn't covered in the bm25
USING clause.

- If the column isn't in the table but is in the USING then Postgres
will throw it's own error before this code is reached.
- If the column is in the table and is isn't in the USING we will get
this error
- If the column isn't in **either** then I suppose we could throw a more
accurate warning, but this way at least it will throw the new erro,
fixing which will result in the PG error

```
pg_search=# create table tester(id int, words text);
CREATE TABLE

pg_search=# CREATE INDEX   
        ON tester USING bm25(id, words) WITH (
    key_field = 'id', 
    numeric_fields = '{
        "missing": {"fast": true}
    }'
) ;
ERROR:  the column `missing` does not exist in the USING clause

pg_search=# CREATE INDEX   
        ON tester USING bm25(id, words, missing) WITH (
    key_field = 'id', 
    numeric_fields = '{
        "missing": {"fast": true}
    }'
) ;
ERROR:  column "missing" does not exist
```