fix: Unify TopN detection across hooks (#4026)
Window function replacement was:
* Not a strict as TopN's order-by's constraints were.
* Not disabling itself when the custom scan was disabled.

Both of these cases lead to errors like:
```
ERROR:  window_agg placeholder should not be executed - custom scan should have intercepted this.
```
...either because the custom scan would run, but couldn't use TopN, or
because it wouldn't run at all.

Our planner hook needs to duplicate a lot of logic contained in
`basescan` planning, but it needs to do so using only a `parse`/`Query`,
rather than using the planning infrastructure provided to `CustomScan`s.
This is error prone, and we should still try and fix it via #3455.

Extracted an `orderby.rs` module in the `customscan` package to
centralize the logic which is now used by the planner hook, `basescan`,
and `aggregatescan`.

Added new tests which failed before, and succeed now.

(cherry picked from commit 6d58de10280bd5e3fbbf1a70242ffec0d76cce42)