fix: Handle aliased indexed expressions in search resolution and top-k order by (#4666)
# Ticket(s) Closed

## What
This PR fixes three issues
- Correctly display aliases for the `literal` tokenizer
- Support aliased tokenized expressions in indexes
- If there are two ambiguous index fields that could be used, we now
throw an error message asking the user to pick one with `pdb.alias`.
 - Support aliased tokenized expressions being pushed down for top k.

## Why
We need to fix these queries that shouldn't fail:

```sql
CREATE INDEX search_idx ON mock_items
USING bm25 (
  id,
  (lower(description)::pdb.literal('alias=literal_description'))
)
WITH (key_field = 'id');

SELECT description, rating, category
FROM mock_items
WHERE description ||| 'sleek running shoes'

ERROR:  query is incompatible with pg_search's `|||` operator: the right-hand side could not be converted to a search query
```

```sql
CREATE INDEX search_idx ON mock_items
USING bm25 (
  id,
  description,
  (lower(description)::pdb.literal('alias=literal_description'))
)
WITH (key_field = 'id');

SELECT description, rating
FROM mock_items
WHERE description ||| 'sleek running shoes'
ORDER BY lower(description)
LIMIT 5;

WARNING:  Query has LIMIT 5 but is not using Top K scan (using Normal instead). Reason: ORDER BY columns cannot be pushed down to the index. This may cause poor performance on large datasets. Remedies: Ensure ORDER BY columns are indexed. Numeric columns are fast by default. For string columns, use pdb.literal tokenizer. To disable this warning: SET paradedb.check_topk_scan = false (table: mock_items)
```

## How

`field_name_from_node` was previously ignoring aliased expressions all
together. To fix the first issue, I updated it to instead collect the
candidate index fields and then return one if one could be unambiguously
identified.

To fix the top k issue, I updated `analyze_sort_expression` to first do
the full fast field check and instead of the quicker `lower` branch so
that the name from the index would be used later on.

## Tests
I added regression tests for all of the issues.